exclude: "/migrations/|staticfiles/|logs/|docker/|static"
default_stages: [ commit ]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
      - id: check-yaml
      - id: fix-encoding-pragma
        args: [ "--remove" ]

  - repo: https://github.com/myint/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        args: [
          "--in-place",
          "--remove-all-unused-imports",
          "--remove-unused-variable",
        ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [ "--py310-plus", "--keep-runtime-typing" ]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        files: '\.py$'

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [
          "flake8-blind-except",
          "flake8-commas",
          "flake8-comprehensions",
          "flake8-deprecated",
          "flake8-broken-line",
          "flake8-bugbear",
          "flake8-tidy-imports",
          "flake8-print",
          "flake8-logging-format",
          "flake8-pytest-style",
          'pyproject-flake8'
        ]
ci:
  autoupdate_schedule: weekly
  skip: [ ]
  submodules: false
